### ISSUE TITLE
Image migration

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#102] opened 2023-03-09 22:15 UTC
I see some images in my-solar-system used in keplers-laws. Can those be moved to solar-system-common?

**Comment by samreid** [comment] 2023-03-11 14:54
@jonathanolson It seems keplers-laws depends on my-solar-system at the moment.  Is that still the long-term vision?  Or will we make it so Kepler's Laws just depends on solar-system-common?
@AgustinVallejo we have scripts for moving files between repos and preserving their commit history (if it helps).

**Comment by AgustinVallejo** [comment] 2023-03-11 14:56
@samreid The dependency on MSS is just temporal, the idea is to eventually migrate everything to SSC. Also, if you could guide me to those migration scripts, that'd be great! Thanks

**Comment by samreid** [comment] 2023-03-11 15:00
The script is https://github.com/phetsims/perennial/blob/master/js/scripts/copy-history-to-different-repo.js.  It has some external dependencies and is a somewhat involved task (see the documentation at the top of the file)--feel free to go for it or wait until someone can collaborate.

**Comment by AgustinVallejo** [comment] 2023-03-13 20:28
Images have been migrated

**Comment by samreid** [comment] 2023-03-14 15:08
Can we double check that this process transmitted history? Not critical for this case, but would be good to make sure that process is working as expected.

**Comment by AgustinVallejo** [comment] 2023-03-14 15:13
Ah but precisely because it wasn't critical and just a handful of images, I just moved them manually with the Webstorm refactor function. Not sure if that transmits history.

**Comment by samreid** [comment] 2023-03-14 19:20
I checked the history of files in my-solar-system and confirmed there is not much useful data in the history, so this seems OK for now.  In the future, moving things between repos we prefer to preserve history, even if it takes a bit longer. Re-closing.

**Closed by samreid** 2023-03-14 19:20 UTC
