### ISSUE TITLE
artifacts seen with Win10 + Chrome when zoomed in

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#309] opened 2023-12-05 14:23 UTC
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1008, with Win10 Chrome, when zoom-in and tabbing through the traversal order, I see artifacts from the words "Measuring Tape" on both screens. Not sure it is worth the time to look into, but I thought I would report. 

- This also happens in published. 

- I don't see this on the mac or with Win10 + FF. 

**Steps to reproduce**
1. On either screen, zoom in a good amount using Control +
2. Use the arrow keys to move to the right and then down OR tab through the traversal order. 

**Visuals**
![Screenshot (3)](https://github.com/phetsims/my-solar-system/assets/87318828/39f3078a-e8eb-41ba-ae9d-f1997efda2e8)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.7 2023-12-01 16:11:20 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language: en-US
Window: 1901x946
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2023-12-05 22:48
This is not a problem that is sim specific.

@jonathanolson @jessegreenberg suggestions?

**Comment by jessegreenberg** [comment] 2023-12-05 23:41
Sorry, I don't know how to fix this. I can produce it easily on Win 10 Chrome.

For some reason it goes away with `renderer: canvas`, but that might have other side effects.

```patch
Subject: [PATCH] focusPanDirection -> limitPanDirection, see https://github.com/phetsims/center-and-variability/issues/564
---
Index: js/common/view/VisibilityControlPanel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/VisibilityControlPanel.ts b/js/common/view/VisibilityControlPanel.ts
--- a/js/common/view/VisibilityControlPanel.ts	(revision b61550030529d3081b07d00f40ce9b59cb5e587a)
+++ b/js/common/view/VisibilityControlPanel.ts	(date 1701819500267)
@@ -57,6 +57,7 @@
       tagName: 'div',
       labelTagName: 'h3',
       labelContent: 'Control Panel',
+      renderer: 'canvas',
 
       // phet-io
       tandem: tandem

```

**Comment by jonathanolson** [comment] 2023-12-05 23:50
No more insight. Seems like a Chrome+Win10 bug (I can reproduce), unlikely a great way to work around it.

**Comment by pixelzoom** [comment] 2023-12-05 23:56
I've promoted this problem to https://github.com/phetsims/scenery/issues/1589.

Since it's not sim-specific, and there is no acceptable workaround... Closing this issue as "won't fix".

**Closed by pixelzoom** 2023-12-05 23:56 UTC
Labels: type:bug
