### ISSUE TITLE
CT This should not be run in the call tree of updateDisplay()

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#189] opened 2023-08-01 14:34 UTC
```
my-solar-system : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1690883811012/phet-io-wrappers/state/?sim=my-solar-system&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1690883811012%22%2C%22timestamp%22%3A1690884045026%7D
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1690883811012/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1690883811012/assert/js/assert.js:28:13)
at assert (Display.ts:1388:14)
at ensureNotPainting (BackboneDrawable.js:233:19)
at markDirtyDrawable (Drawable.js:376:28)
at markDirty (SVGBlock.js:195:9)
at markDirtyDrawable (Drawable.js:376:28)
at markDirty (TextStatefulDrawable.js:50:11)
at markPaintDirty (TextStatefulDrawable.js:74:11)
at markDirtyBounds (Text.ts:351:59)
at invalidateText (Text.ts:411:9)
at invalidateFill (Paintable.ts:124:13)
at setFill (Paintable.ts:129:44)
at text (NavigationBarScreenButton.ts:174:8)
at (Multilink.ts:111:20)
at (TinyEmitter.ts:122:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (DerivedProperty.ts:157:12)
at (TinyEmitter.ts:122:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:363:46)
at listener (PropertyStateHandler.ts:281:40)
at attemptToApplyPhases (PropertyStateHandler.ts:201:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:96:11)
at (TinyEmitter.ts:122:18)
at emit (Emitter.ts:61:21)
at emit (PhetioStateEngine.ts:273:25)
at setState (PhetioStateEngine.ts:284:9)
at setFullState (phetioEngine.ts:1063:64)
at apply (phetioCommandProcessor.ts:420:50)
at processCommand (phetioCommandProcessor.ts:298:35)
at getReturn (phetioCommandProcessor.ts:302:15)
at map (phetioCommandProcessor.ts:296:29)
at processCommands (phetioCommandProcessor.ts:238:15)
at addEventListener (phetioCommandProcessor.ts:193:11)
at (phetioCommandProcessor.ts:536:31)
id: Sparky Playwright Firefox
Snapshot from 8/1/2023, 3:56:51 AM

----------------------------------

my-solar-system : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1690883811012/phet-io-wrappers/state/?sim=my-solar-system&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1690883811012%22%2C%22timestamp%22%3A1690894240388%7D
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1690883811012/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1690883811012/assert/js/assert.js:28:13)
at assert (Display.ts:1388:14)
at ensureNotPainting (BackboneDrawable.js:233:19)
at markDirtyDrawable (Drawable.js:376:28)
at markDirty (SVGBlock.js:179:9)
at markDirtyGroup (SVGGroup.js:181:17)
at markDirty (SVGGroup.js:201:11)
at (TinyEmitter.ts:122:18)
at emit (Node.ts:2797:26)
at (TinyEmitter.ts:122:18)
at emit (Transform3.js:102:23)
at invalidate (Transform3.js:74:9)
at setMatrix (Node.ts:2739:20)
at setMatrix (Node.ts:2746:9)
at (MultiListener.js:121:6)
at (TinyEmitter.ts:122:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:363:46)
at listener (PropertyStateHandler.ts:281:40)
at attemptToApplyPhases (PropertyStateHandler.ts:201:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:96:11)
at (TinyEmitter.ts:122:18)
at emit (Emitter.ts:61:21)
at emit (PhetioStateEngine.ts:273:25)
at setState (PhetioStateEngine.ts:284:9)
at setFullState (phetioEngine.ts:1063:64)
at apply (phetioCommandProcessor.ts:420:50)
at processCommand (phetioCommandProcessor.ts:298:35)
at getReturn (phetioCommandProcessor.ts:302:15)
at map (phetioCommandProcessor.ts:296:29)
at processCommands (phetioCommandProcessor.ts:238:15)
at addEventListener (phetioCommandProcessor.ts:193:11)
at (phetioCommandProcessor.ts:536:31)
id: Sparky Playwright Firefox
Snapshot from 8/1/2023, 3:56:51 AM
```

**Comment by jonathanolson** [comment] 2023-09-15 20:21
This looks like it is caused by https://github.com/phetsims/my-solar-system/issues/190, if phet-io eats that error, it will respond with the above errors. @KatieWoe let me know if this error does not go away after the above tagged fix.

**Comment by pixelzoom** [comment] 2023-10-03 17:49
There's no evidence of this on CT. It looks like this was fixed, but there was no followup. So I'm going to close this issue.

**Closed by pixelzoom** 2023-10-03 17:49 UTC
Labels: type:automated-testing
