### ISSUE TITLE
Difficulty Interacting/Moving with Measuring Tape while highlighted: alt-input

### ISSUE THREAD

**Issue by veillette** [phetsims/my-solar-system#142] opened 2023-04-07 17:23 UTC
For https://github.com/phetsims/qa/issues/927

**Test device**
Dell XPS 15

**Operating System**
Windows 10

**Browser**
Chrome

**Problem description**
Difficulty interacting with measuring tape while highlighted.

**Steps to reproduce**
1. Turn  on visibility of checkbox for the  measuring tape.
2. Using the tab key, select the measuring tape.
3. Attempt to move the measuring tape with the arrows key

One would expect the measuring tape to move, but there is no motion. In addition, I could not figure out how to access the tip of the measuring tape with alternative input.

@AgustinVallejo demonstrated to me the "proper" way to interact with the measuring tape.

1. Turn on visibility of checkbox for the  measuring tape.
2. Using the tab key, select the measuring tape.
3.  **Press Enter** 
4. One can successfully move the measuring tape with the arrows key

If one presses enter, then one can then access the tip of the measuring tape. 

Oddly to me, for someone that is new to QA and alternative input, if one tabs away from the measuring tape, one can come back to the measuring tape and interact with it, without pressing the enter key. The tip is then integrated in the sequence of interactive highlights. In other words, the enter key has somehow permanently unlocked its behavior on a given screen (even after pressing the reset all button).

I suspect this behavior is not due to my-solar-system but  intrinsic to the measuring tape.  I could not find a recent published simulation that make uses of a measuring tape with alternative input enabled. 

Assigning to @AgustinVallejo to discuss if this should be elevated to a common-code issue, or if it should be deferred for MSS.

**Comment by samreid** [comment] 2023-04-07 20:37
`moveToFront` in `baseStart` in MeasuringTapeNode.ts is causing this bug. Is it a known problem that focus/keyboard interaction is disrupted by `moveToFront`?

**Comment by samreid** [comment] 2023-04-07 20:42
This patch only runs `moveToFront` for the mouse/touch and does not run it for keyboard drag start.  It works around the bug in this issue.

<details>

```diff

Subject: [PATCH] Update wording in the validation error message, see https://github.com/phetsims/density/issues/154
---
Index: js/MeasuringTapeNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/MeasuringTapeNode.ts b/js/MeasuringTapeNode.ts
--- a/js/MeasuringTapeNode.ts	(revision 29e73ac6c9191a78ebcb842465e88d07551db17b)
+++ b/js/MeasuringTapeNode.ts	(date 1680900037523)
@@ -313,7 +313,6 @@
       tip.interactiveHighlightEnabled = true;
 
       const baseStart = () => {
-        this.moveToFront();
         options.baseDragStarted();
         this._isBaseUserControlledProperty.value = true;
       };
@@ -344,6 +343,7 @@
       this.baseDragListener = new DragListener( {
         tandem: options.tandem.createTandem( 'baseDragListener' ),
         start: event => {
+          this.moveToFront();
           baseStart();
           const position = this.modelViewTransformProperty.value.modelToViewPosition( this.basePositionProperty.value );
           baseStartOffset = event.currentTarget!.globalToParentPoint( event.pointer.point ).minus( position );
@@ -422,7 +422,6 @@
         transform: this.modelViewTransformProperty,
         shiftDragVelocity: 150,
         start: () => {
-          this.moveToFront();
           this._isTipUserControlledProperty.value = true;
         },
         end: tipEnd

```

</details>

I left the bug in master in case it helps @jessegreenberg @zepumph or @jonathanolson reproduce the problem in common code.  But maybe we could also commit this workaround and create an isolated test case for this problem.

**Comment by jessegreenberg** [comment] 2023-04-07 20:47
`moveToFront` is probably totally removing the Node and its PDOM element then adding it back in, which could disrupt focus.
PDOMTree should be handling this for us, I am not sure why it isn't working. I can take a look soon.

Until then, another workaround could be to move it to front on `focus` instead of on the start of drag.

**Comment by samreid** [comment] 2023-04-07 21:39
To test @jessegreenberg hypothesis, I ran this patch:

<details>

```diff

Subject: [PATCH] Update wording in the validation error message, see https://github.com/phetsims/density/issues/154
---
Index: js/accessibility/pdom/PDOMInstance.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/pdom/PDOMInstance.ts b/js/accessibility/pdom/PDOMInstance.ts
--- a/js/accessibility/pdom/PDOMInstance.ts	(revision ac6c516de85dde8c0ea08f4d00f86e404fedef41)
+++ b/js/accessibility/pdom/PDOMInstance.ts	(date 1680903533077)
@@ -498,7 +498,7 @@
         // Reorder DOM elements in a way that doesn't do any work if they are already in a sorted order.
         // No need to reinsert if `element` is already in the right order
         if ( primarySibling.childNodes[ i ] !== element ) {
-          primarySibling.insertBefore( element, primarySibling.childNodes[ i + 1 ] );
+          // primarySibling.insertBefore( element, primarySibling.childNodes[ i + 1 ] );
         }
 
         // Decrement so that it is easier to place elements using the browser's Node.insertBefore API

```

</details>

And observed that the measuring tape (correctly) did not lose focus.

**Comment by samreid** [comment] 2023-04-07 21:52
This approach is also not buggy in this context. It avoids `insertNode` on a focused element:

<details>

```diff

Subject: [PATCH] Update wording in the validation error message, see https://github.com/phetsims/density/issues/154
---
Index: js/accessibility/pdom/PDOMInstance.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/pdom/PDOMInstance.ts b/js/accessibility/pdom/PDOMInstance.ts
--- a/js/accessibility/pdom/PDOMInstance.ts	(revision ac6c516de85dde8c0ea08f4d00f86e404fedef41)
+++ b/js/accessibility/pdom/PDOMInstance.ts	(date 1680904039953)
@@ -487,6 +487,8 @@
     // added to a single parent DOMElement (this PDOMInstance's PDOMPeer's primarySibling)
     let i = primarySibling.childNodes.length - 1;
 
+    const focused = document.activeElement;
+
     // Iterate through all PDOMInstance children
     for ( let peerIndex = this.children.length - 1; peerIndex >= 0; peerIndex-- ) {
       const peer = this.children[ peerIndex ].peer!;
@@ -497,7 +499,7 @@
 
         // Reorder DOM elements in a way that doesn't do any work if they are already in a sorted order.
         // No need to reinsert if `element` is already in the right order
-        if ( primarySibling.childNodes[ i ] !== element ) {
+        if ( primarySibling.childNodes[ i ] !== element && element !== focused ) {
           primarySibling.insertBefore( element, primarySibling.childNodes[ i + 1 ] );
         }
 


```

</details>

Perhaps we can use the "focused" element as an anchoring element, and leave it in-place and `insertBefore` on all the other nodes around it?

**Comment by jessegreenberg** [comment] 2023-04-10 15:16
Starting to look into this. I want to understand why it doesn't happen in the scenery-phet demo, and also why pressing "Enter" before moving the base makes the problem go away in this sim. I don't see any listeners in the component or sim that would cause that part.

**Comment by samreid** [comment] 2023-04-10 15:20
> and also why pressing "Enter" before moving the base makes the problem go away in this sim

I believe the first `moveToFront` removes the PDOM and loses focus.  Subsequent `moveToFront` are no-op since it is already in the front.  I'll be on slack if you want to collaborate.

**Comment by jessegreenberg** [comment] 2023-04-10 15:44
OK, thanks - I can reproduce the bug in demo with this patch:
```patch
Subject: [PATCH] Use Checkbox directly, remove superclass, see https://github.com/phetsims/gravity-force-lab-basics/issues/324"
---
Index: js/demo/components/demoMeasuringTapeNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/demo/components/demoMeasuringTapeNode.ts b/js/demo/components/demoMeasuringTapeNode.ts
--- a/js/demo/components/demoMeasuringTapeNode.ts	(revision 29e73ac6c9191a78ebcb842465e88d07551db17b)
+++ b/js/demo/components/demoMeasuringTapeNode.ts	(date 1681141275918)
@@ -15,7 +15,7 @@
 
   const measuringTapeUnitsProperty = new Property( { name: 'meters', multiplier: 1 } );
 
-  return new MeasuringTapeNode( measuringTapeUnitsProperty, {
+  const tapeNode = new MeasuringTapeNode( measuringTapeUnitsProperty, {
     textColor: 'black',
     textBackgroundColor: 'rgba( 255, 0, 0, 0.1 )', // translucent red
     textBackgroundXMargin: 10,
@@ -25,4 +25,13 @@
     basePositionProperty: new Vector2Property( new Vector2( layoutBounds.centerX, layoutBounds.centerY ) ),
     tipPositionProperty: new Vector2Property( new Vector2( layoutBounds.centerX + 100, layoutBounds.centerY ) )
   } );
+
+  const otherFocusable = new phet.scenery.Circle( '25', {
+    fill: 'red',
+    tagName: 'button'
+  } );
+
+  return new phet.scenery.Node( {
+    children: [ tapeNode, otherFocusable ]
+  } );
 }
\ No newline at end of file

```

Pressing "Enter" in this example has no impact on the behavior. In my-solar-system, I don't see `moveToFront()` called when "Enter" is pressed which is why I am confused about that input.

**Comment by samreid** [comment] 2023-04-10 21:59
@jessegreenberg @jonathanolson and I addressed this in the commit. This fix addresses the use case in MSS and other sims like it, and @jessegreenberg will open a more general issue about the deeper problem which does not need to be solved for MSS.  Closing.

**Closed by samreid** 2023-04-10 21:59 UTC
Labels: design:alt-input
