### ISSUE TITLE
Touch areas overlap

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#324] opened 2024-01-03 14:09 UTC
For https://github.com/phetsims/qa/issues/1015, on the Lab Screen, the touch areas for the increment/decrement buttons and the Follow Center of Mass button overlap:

<img width="865" alt="Screenshot 2024-01-03 at 9 05 35 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/a9002001-0b73-4400-8b7d-21465ea1a8ab">

**Comment by AgustinVallejo** [comment] 2024-01-03 15:03
Reduced the touch areas horizontal dilation, please review and mark as ready to cherry pick if ready. Thanks @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment] 2024-01-04 15:22
looks good to me 🙂

**Comment by Nancy-Salpepi** [comment] 2024-01-04 15:26
Sorry @AgustinVallejo I edited my comment above.

**Comment by AgustinVallejo** [comment] 2024-01-04 16:06
Fixed the overlap with home button. Assigning back

**Comment by Nancy-Salpepi** [comment] 2024-01-04 16:55
OK. Now all looks good. Thanks!

**Comment by Nancy-Salpepi** [comment] 2024-01-11 14:09
The touch areas I originally reported all look good. 
I'm sorry I didn't see this before, but when I zoom in, it looks like the touch areas of the increment or decrement buttons overlap.
<img width="175" alt="Screenshot 2024-01-11 at 9 05 52 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/04d7e010-0362-4baf-a201-40f47c2fe025">
<img width="175" alt="Screenshot 2024-01-11 at 9 06 01 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/f994e682-14ff-4946-bf3a-039ffedaede9">

**Comment by AgustinVallejo** [comment] 2024-01-11 17:11
This is weird. I tried editing the touch area dilation but it doesn't seem to be changing neither in `SolarSystemCommonNumberControl.ts` nor in `NumberControl.ts`, even by changing the default values. In fact, trying other options like 'leftStart' just outright fails. Going to check with other devs to see if this is a common code fault. If so, I can leave the correct options sitting there, but this wouldn't be fixed until we fix the common code component.

**Comment by AgustinVallejo** [comment] 2024-01-12 17:36
@jonathanolson helped me correct this in common code. Can you check in main and mark as ready for cherry pick when done? Thanks!

**Comment by Nancy-Salpepi** [comment] 2024-01-12 21:49
Looks good on main

**Comment by AgustinVallejo** [comment] 2024-01-17 19:53
This has been cherry picked into the 1.3 branch.

**Comment by Nancy-Salpepi** [comment] 2024-01-18 14:37
Touch areas no longer overlap, but the width of the area has been decreased and is off-center now.
<img width="367" alt="Screenshot 2024-01-18 at 9 18 55 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/fa54f8b0-c947-482c-9cec-6aaacbaa7760">

I'm only mentioning this because you said you made this change in common code. Not sure what the next step should be here. Perhaps publish MSS as is, but go back and fix the common code? 

Here is Geometric Optics on main vs. published:
<img width="650" alt="Screenshot 2024-01-18 at 9 30 33 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/2cc5d028-2b35-459d-9bc0-fa4972dcb1e0">
<img width="650" alt="Screenshot 2024-01-18 at 9 31 28 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/d52ce4cf-3f6e-449d-963b-f191fb9962f1">

**Comment by AgustinVallejo** [comment] 2024-01-18 15:10
I believe this is the original intended behavior, but the way it was implemented in common code didn't enforce it properly. @pixelzoom and I fixed it. So I'm not sure what to do about the other affected sims. @pixelzoom?

**Comment by pixelzoom** [comment] 2024-01-18 18:51
Self assigning to have a look.

**Comment by pixelzoom** [comment] 2024-01-19 17:32
> I believe this is the original intended behavior, but the way it was implemented in common code didn't enforce it properly. @pixelzoom and I fixed it. So I'm not sure what to do about the other affected sims. @pixelzoom?

I was not involved in this. Did you mean "@jonathanolson and I fixed it" ?

Reviewing the change... It was risky/inappropriate to change this in for all sims by changing NumberControl in https://github.com/phetsims/scenery-phet/commit/01595a20b6316d7a6e329ceef7e6ec967321be00. I recommend reverting that commit.   

You can address this in a sim-specific way by doing one of the following:
(a) Increase the vertical space between NumberControls in the sim.  
(b) Use NumberControlOptions.arrowButtonOptions to set your own pointer areas for the arrow buttons.

**Comment by pixelzoom** [comment] 2024-01-19 17:44
> It was risky/inappropriate to change this in for all sims by changing NumberControl

To clarify... The change the you made is relevant only for this layout of NumberControl, and NumberControl supports flexible layouts.  So shifting the touch areas as you've done in this change (via `touchAreaXShift` and `mouseAreaXShift`) is inappropriate.  So I'm going to revert https://github.com/phetsims/scenery-phet/commit/01595a20b6316d7a6e329ceef7e6ec967321be00 before this problem sneaks into other sims.

**Comment by pixelzoom** [comment] 2024-01-19 18:28
After investigating futher, I have reapplied https://github.com/phetsims/scenery-phet/commit/01595a20b6316d7a6e329ceef7e6ec967321be00.  It is indeed appropriate for all sims, because it fixes a bug is present in all sims.

Back in 4/2019, https://github.com/phetsims/scenery-phet/issues/489 changed the arrow button pointer areas to be purposedly shifted, so that they do not interfer/overlap with the slider thumb.  That seems to have been broken for a long time.  And as @Nancy-Salpepi observed in https://github.com/phetsims/my-solar-system/issues/324#issuecomment-1898602413, that bug is present in published in sims, and is fixed in main by https://github.com/phetsims/scenery-phet/commit/01595a20b6316d7a6e329ceef7e6ec967321be00.

So... I believe that NumberControl is now working correctly in general, and in MSS.  And this issue can be closed.   I don't know if https://github.com/phetsims/scenery-phet/commit/01595a20b6316d7a6e329ceef7e6ec967321be00 need to be applied to MSS release branch, so back to @AgustinVallejo.

**Comment by AgustinVallejo** [comment] 2024-01-29 21:26
This is done in the released version. Closing

**Closed by AgustinVallejo** 2024-01-29 21:26 UTC
Labels: type:bug, status:fixed-awaiting-deploy
